### PR TITLE
Make footer look better on mobile

### PR DESCRIPTION
**Pull request by evanlucas**
Before:

screen shot 2015-08-30 at 8 33 46 am

After:

screen shot 2015-08-30 at 8 33 24 am

### CODE REVIEW

**Comment by fhemberger** [comment]
@evanlucas Have you changed the SVG file as well? If so, please add the file to the PR as well (put it in /static/images) and use [svgo](https://github.com/svg/svgo) to optimize it before including it as base64. Thanks!

**Comment by evanlucas** [comment]
I did not change it at all. It is the exact same as the non-mobile one

**Comment by fhemberger** [comment]
Okay, then there's no need to include the file again, please just change the background-position in the media-query.

**Comment by evanlucas** [comment]
ah ok

**Comment by evanlucas** [comment]
Done

**Comment by fhemberger** [comment]
Cool, thanks!

**Pull request merged**
