### PR TITLE
added legacy resources for old v12.x docs/

### PR DESCRIPTION
**Pull request by rvagg**

### CODE REVIEW

**Comment by rvagg** [comment]
to make the likes of https://nodejs.org/docs/v0.12.7/ happy, last outstanding item prior to switch-over I think, anyone around to lgtm this?

**Comment by rvagg** [comment]
added syntax highlighting JS and now v0.12.7 docs resolve all their resources cleanly and render as per old site

**Comment by rvagg** [comment]
merged, sorry @nodejs/website, I just want to get this done ..

**Comment by fhemberger** [comment]
Thanks!

**Pull request merged**
