### PR TITLE
Node versions before iojs

### PR DESCRIPTION
**Pull request by phillipj**
Addresses @rvagg [comment](https://github.com/nodejs/new.nodejs.org/issues/58#issuecomment-136496901) in #58 about having v0.12.7 as current version instead of v3.2.0.

Wait until node v4 is out before sorting combined node and iojs versions by semver.

### CODE REVIEW

**Comment by fhemberger** [comment]
We can keep the script unchanged, just replace `source/versions.json` with `https://new.nodejs.org/dist/index.json`.

Or we just change https://github.com/nodejs/new.nodejs.org/blob/master/build.js#L55 to `v0.12.7` for now.

**Comment by phillipj** [comment]
> We can keep the script unchanged, just replace source/versions.json with https://new.nodejs.org/dist/index.json.

Ahh, so we're okey with just having node version at first?

**Comment by phillipj** [comment]
> Or we just change https://github.com/nodejs/new.nodejs.org/blob/master/build.js#L55 to v0.12.7 for now.

What I did initially but it felt **really** confusing displaying table of previous releases.. Having node versions at the top wasnt that disturbing.

**Comment by fhemberger** [comment]
> Ahh, so we're okey with just having node version at first?

To be honest: I don't know. ;) /cc @mikeal

**Comment by rvagg** [comment]
yes please, v0.12 first please, v4 will be out later this week or at the start of next week so it won't matter for long anyway

**Comment by phillipj** [comment]
Alright, closing this as @fhemberger just pushed a fix to master instead

**Pull request closed without merging**
