### PR TITLE
Optimize Performance

### PR DESCRIPTION
**Pull request by fhemberger**
Used Google web-font loader and moved uncritical CSS out of the render path.

PageSpeed Insights before:
**Mobile:** 72/100, 98/100 (Usability)
**Desktop:** 88 / 100

PageSpeed Insights after:
**Mobile:** 90/100, 99/100 (Usability)
**Desktop:** 96/100

### CODE REVIEW

**Comment by fhemberger** [comment]
Merge conflict is because of 5511f3c, rebased with master, don't know why git still sees conflicts here.
I'd really like to merge this change into master, because of the notable performance improvement.

cc @nodejs/website

**Comment by mikeal** [comment]
+1 although I wish there was an easy way to test to make sure analytics is still working the same.

**Comment by fhemberger** [comment]
I thoroughly read that piece of analytics code a few times before I decided to merge it, looked okay for me. The generated code is also used by the H5BP, gulp and hapi projects.

**Comment by mikeal** [comment]
Sounds good then. +1 :)

**Comment by fhemberger** [comment]
Cherry picked changes into master.

**Pull request closed without merging**
