### PR TITLE
Automating release post

### LINKED ISSUE #47: Automated release posts
So, we have the releases .json file from build, if we also got the latest Changelog.md we could automatically generate the release blog posts rather than the manual ones we currently have which are quite a pain in the ass.

### PR DESCRIPTION
**Pull request by phillipj**
Stitches data from different sources into a release blog post about the latest version released. Its in dire need for some testing, I could take a look at that after getting some feedback on it as is.

Closes #47.

Generated for v0.12.7:

```markdown
---
date: 2015-09-04T06:53:17.662Z
version: 0.12.7
category: release
title: Node v0.12.7 (Stable)
slug: node-v0-12-7-stable
layout: blog-post.hbs
---

## 2015-07-09, Version 0.12.7 (Stable)

### Commits

* [[`0cf9f27703`](https://github.com/nodejs/node/commit/0cf9f27703)] - **deps**: upgrade openssl sources to 1.0.1p [#25654](https://github.com/joyent/node/pull/25654)
* [[`8917e430b8`](https://github.com/nodejs/node/commit/8917e430b8)] - **deps**: upgrade to npm 2.11.3 [#25545](https://github.com/joyent/node/pull/25545)
* [[`88a27a9621`](https://github.com/nodejs/node/commit/88a27a9621)] - **V8**: cherry-pick JitCodeEvent patch from upstream (Ben Noordhuis) [#25589](https://github.com/joyent/node/pull/25589)
* [[`18d413d299`](https://github.com/nodejs/node/commit/18d413d299)] - **win,msi**: create npm folder in AppData directory (Steven Rockarts) [#8838](https://github.com/joyent/node/pull/8838)



Source Code: http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz

Macintosh Installer (Universal): http://nodejs.org/dist/v0.12.7/node-v0.12.7.pkg

Windows Installer: http://nodejs.org/dist/v0.12.7/node-v0.12.7-x86.msi

Windows x64 Installer: http://nodejs.org/dist/v0.12.7/x64/node-v0.12.7-x64.msi

Windows x64 Files: http://nodejs.org/dist/v0.12.7/x64/

Linux 32-bit Binary: http://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x86.tar.gz

Linux 64-bit Binary: http://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz

Solaris 32-bit Binary: http://nodejs.org/dist/v0.12.7/node-v0.12.7-sunos-x86.tar.gz

Solaris 64-bit Binary: http://nodejs.org/dist/v0.12.7/node-v0.12.7-sunos-x64.tar.gz

Other release files: http://nodejs.org/dist/v0.12.7/

Website: http://nodejs.org/docs/v0.12.7/

Documentation: http://nodejs.org/docs/v0.12.7/api/

Shasums:
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

37af2e7e748a81921f8956f1938dc5977e422ed8  node-v0.12.7-darwin-x64.tar.gz
8bf1caba4d474bfbff75a75c6b3fc1e413e34a8e  node-v0.12.7-darwin-x86.tar.gz
0a861a6ded50c8cda32ac39c3a54699c767742e6  node-v0.12.7-linux-x64.tar.gz
cb2ba2e004fc03f634e56618194e4c2c025cfe22  node-v0.12.7-linux-x86.tar.gz
eb79ed6811ce07743d64b3fb16d762dcbb40a91f  node-v0.12.7-sunos-x64.tar.gz
5a706660fd9392274c8c7d8f21bcebbf7735d1f4  node-v0.12.7-sunos-x86.tar.gz
7aa06c0d54c97e5193bafc927dbe1bede308da97  node-v0.12.7-x86.msi
f6d9b8865905f4f419a9228a960af061f69a6fd5  node-v0.12.7.pkg
6d59007212a964c7a4defc5520aedacdbcb008e1  node-v0.12.7.tar.gz
fac6dbd4b88451228b93d8c217b20de2759cb116  node.exe
05ceb63dce379bc71c9726635efcb95983bac891  node.exp
4b38821ec6ca2dd77637516f11f92637551987ce  node.lib
a7c984b68063571f53bc5782cf30c94f1b32d2ec  node.pdb
cb10067b40b9db47ed1873850ddc96d0c913e985  openssl-cli.exe
bad044c9864ba0181094bbc6d9f6ebe55ceb9e91  openssl-cli.pdb
05cfffda323563c42ff2e461a8e98ee984ad15d1  x64/node-v0.12.7-x64.msi
55e8a906450bf7027808e6cdff259bafd1844306  x64/node.exe
7c04fddb306c69d1701cf2f52cc89c6098894d6f  x64/node.exp
ac2985d01aa77eef104db97d583eef5018430a1b  x64/node.lib
8761ac5ad6074e7c559641572cf19ca2f3e8ea98  x64/node.pdb
6724328166b1e3a2c967023759ee50d0c2d076b3  x64/openssl-cli.exe
e377127c7c2d5eae46228074879c6fa77d9fa221  x64/openssl-cli.pdb
-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - https://gpgtools.org

iQIcBAEBCgAGBQJVnwkCAAoJEFCjBR+IjGKN48IP/A2aw749kfIzMN5X1x90rTfu
1OoMPFyp5a3Tg4nq9cbiBHQd6oWsMOqiPLiK+cgxtFtPz9cMTvJwDtZlcE6jD+5T
Dbo756zmUGz3euJcpKGVag/Nr+hx8X7ADHLdbaHv5RmJ17aQ/zIRxe9lt+8xrK0g
Ms4my5QfJV5w7+eheDw8/71vHSaUoGbW44PWV98ub74NPdPLnlyvRIFqs//rRahX
VduAq/BepH3CWhTEgMeMu4fEPLiIXgEna5GaFQ1zg5/B4XaJuFNiDP6xede7VQwt
VkwtrTl1yMkH6Guw6f0hrdFalTa3E9SELIQCnZDKj2fT3eJUdtHg82TmrIU/v934
FOFNSU07CJOI8H3cFPEgFtbf05Eyh2axZq/GFvgTMIKpaAtK66RF4/vpoWvezyK0
yIou+59zhL2n3tdO5OUZzZ47843sT2UXH+pOB7xmCu4EYhCve0pPZf30UXzYU46P
RQEsLRIhVPPYszCnStYMWroLBF2zfprbn5pILCYtJbeafFz3U20IbFgPhc7xnWtQ
FiJS0lNdjc8B0yZIiTg59FyudADojWu37gXCYGlD9pyb03GSzG7CIPr206rNwjcR
gW0cbSCtfDdiTo0Za6+ZZdhMW2mf+7MwW2LdXiJiWasj8gAQeIXqXJiWdxQLb2ZV
uAV+X2VgKWk7UCom3i/Y
=fmln
-----END PGP SIGNATURE-----
```

### CODE REVIEW

**Comment by fhemberger** [comment]
Haven't tested it yet, but this looks pretty awesome!

**Comment by rvagg** [comment]
I can see some problems here but not time just yet to comment, the node v4 release is going to have a structure more similar to io.js than 0.12, including the files that will be dropped, also we have a pretty mature changelog format from io.js that we'll be using

**Comment by phillipj** [comment]
Thanks for your initial thoughts @rvagg! It handles io.js changelog format already. I'll change the files list too resemble iojs' instead.

Any other thoughts?

Just generated for v3.3.0 after changing versions `index.json` and shasum URLs -> iojs.org:

```markdown
---
date: 2015-09-04T11:43:52.691Z
version: 3.3.0
category: release
title: Node v3.3.0 (Stable)
slug: node-v3-3-0-stable
layout: blog-post.hbs
---

## 2015-09-02, Version 3.3.0, @rvagg

### Notable changes

* **build**: Add a `--link-module` option to `configure` that can be used to bundle additional JavaScript modules into a built binary (Bradley Meck) [#2497](https://github.com/nodejs/node/pull/2497)
* **docs**: Merge outstanding doc updates from joyent/node (James M Snell) [#2378](https://github.com/nodejs/node/pull/2378)
* **http_parser**: Significant performance improvement by having `http.Server` consume all initial data from its `net.Socket` and parsing directly without having to enter JavaScript. Any `'data'` listeners on the `net.Socket` will result in the data being "unconsumed" into JavaScript, thereby undoing any performance gains. (Fedor Indutny) [#2355](https://github.com/nodejs/node/pull/2355)
* **libuv**: Upgrade to 1.7.3 (from 1.6.1), see [ChangeLog](https://github.com/libuv/libuv/blob/v1.x/ChangeLog) for details (Saúl Ibarra Corretgé) [#2310](https://github.com/nodejs/node/pull/2310)
* **V8**: Upgrade to 4.4.63.30 (from 4.4.63.26) (Michaël Zasso) [#2482](https://github.com/nodejs/node/pull/2482)

### Known issues

See https://github.com/nodejs/io.js/labels/confirmed-bug for complete and current list of known issues.

* Some uses of computed object shorthand properties are not handled correctly by the current version of V8. e.g. `[{ [prop]: val }]` evaluates to `[{}]`. [#2507](https://github.com/nodejs/node/issues/2507)
* Some problems with unreferenced timers running during `beforeExit` are still to be resolved. See [#1264](https://github.com/nodejs/io.js/issues/1264).
* Surrogate pair in REPL can freeze terminal. [#690](https://github.com/nodejs/io.js/issues/690)
* `process.send()` is not synchronous as the docs suggest, a regression introduced in 1.0.2, see [#760](https://github.com/nodejs/io.js/issues/760).
* Calling `dns.setServers()` while a DNS query is in progress can cause the process to crash on a failed assertion. [#894](https://github.com/nodejs/io.js/issues/894)
* `url.resolve` may transfer the auth portion of the url when resolving between two full hosts, see [#1435](https://github.com/nodejs/io.js/issues/1435).

### Commits

* [[`1a531b4e44`](https://github.com/nodejs/node/commit/1a531b4e44)] - **(SEMVER-MINOR)** Introduce --link-module to ./configure (Bradley Meck) [#2497](https://github.com/nodejs/node/pull/2497)
* [[`d2f314c190`](https://github.com/nodejs/node/commit/d2f314c190)] - **build**: fix borked chmod call for release uploads (Rod Vagg) [#2645](https://github.com/nodejs/node/pull/2645)
* [[`3172e9c541`](https://github.com/nodejs/node/commit/3172e9c541)] - **build**: set file permissions before uploading (Rod Vagg) [#2623](https://github.com/nodejs/node/pull/2623)

+ alot more commits omitted for brevity's sake in this example


Source Code: http://nodejs.org/dist/v3.3.0/node-v3.3.0.tar.gz

Macintosh Installer (Universal): http://nodejs.org/dist/v3.3.0/node-v3.3.0.pkg

Windows Installer: http://nodejs.org/dist/v3.3.0/node-v3.3.0-x86.msi

Windows x64 Installer: http://nodejs.org/dist/v3.3.0/x64/node-v3.3.0-x64.msi

Windows x64 Files: http://nodejs.org/dist/v3.3.0/x64/

Linux 32-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-x86.tar.gz

Linux 64-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-x64.tar.gz

Solaris 32-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-sunos-x86.tar.gz

Solaris 64-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-sunos-x64.tar.gz

Other release files: http://nodejs.org/dist/v3.3.0/

Website: http://nodejs.org/docs/v3.3.0/

Documentation: http://nodejs.org/docs/v3.3.0/api/

Shasums:
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

3ec6fb8d7a9ad30f673a8e114a98b2dcd6b802a375b87e5b3039dac51a967423  iojs-v3.3.0-darwin-x64.tar.gz
c52bc752d2b0af38c4e8ffc83a6132df7e4ff84775db2ecaaa71893a873d4cdf  iojs-v3.3.0-darwin-x64.tar.xz
36136360c082a6cb0753b338f76ac110d2b183846a9df2e8934bb5257675d35b  iojs-v3.3.0-headers.tar.gz
3067437c9338c0415fe721fa5a67995f9435e6f313b4fab00a65f28e824ecafa  iojs-v3.3.0-headers.tar.xz
571b12fa6fcf658873ee556fc61edab07c12daae092cfe6bdeb173df3449214c  iojs-v3.3.0-linux-armv6l.tar.gz
6c210d78728c51a69ab6fdbf096c69d3632897bcc4eed4c60958e34b642ed53f  iojs-v3.3.0-linux-armv6l.tar.xz
af44c0644128a552896247866e283d3991934025eee4bdc8c288439bb8d5516f  iojs-v3.3.0-linux-armv7l.tar.gz
688b4506efaf2fb330c6b3d6dbe80f47af60df2cdaf24f47f0ed966d01815819  iojs-v3.3.0-linux-armv7l.tar.xz
c9b1c51b7cc780c19df504e29e26b27ee89f7bf6f8d601da597f52e7e39767fd  iojs-v3.3.0-linux-x64.tar.gz
add2cd394886d7d3a92bc84e9af6e4a0d509060f0b63bf4b11de6471046043e8  iojs-v3.3.0-linux-x64.tar.xz
197716f55592c85e04f644f9e2ef0d276cf90fecba3cf0e01bad6d3d628446dd  iojs-v3.3.0-linux-x86.tar.gz
a4ef6de573441b50bffe8a82f66ebf941a238f175d9decc3d021a615110722d4  iojs-v3.3.0-linux-x86.tar.xz
db18a6029c8b9fdc0b95287b1a51e4ea753b515f3f7799e4a5f85ff67ef7a036  iojs-v3.3.0.pkg
e84a649858e6f5c1458c0d5d7bf1952f78e93a26ea6bc519222e92e43e2fadde  iojs-v3.3.0.tar.gz
8b317162af3e0e81b3f5efcda664e5f3525e6e1ab4c21b446db83cf9c4028a32  iojs-v3.3.0.tar.xz
68289641c2780e8c34fc9d4c1c92290d5adb7612b4979722523d6212c79bb0d0  iojs-v3.3.0-x64.msi
1d692b5427d6c27dcdff6fe500e209a3d44de4c069d63e5213457986ffae727d  iojs-v3.3.0-x86.msi
0ecb7cd753e55e611ab2235f97ce59205486af4f157b2396ba74c8405e89d622  win-x64/iojs.exe
9b4e1cbe8e731d14f39d006613482ddd143c6c7f7e77d41f37fc8dc231a0ab24  win-x64/iojs.lib
27e8129adc45c7e4cbfbbf59db419c3f7ba0a8a03bee7532e3d2030c1c178680  win-x86/iojs.exe
6c7c3508599353f2718c37f50db74950a64021df625a3ad407b8848099f7f1e1  win-x86/iojs.lib
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJV5uz/AAoJEMJzeS99g1Rdsx0H/0XR2EIUlaT8g6hyYhwlB3Wo
dhwoDm5z1/NcjTiCS5eGZm9WvPV+2kfMAbY02+01hcdl1oNSZ3BgIqyHZQtLDEd9
y/S+QnH33VaLWbWjs0r2oeF9E8ifGLPYiR/4DPE4VhcbZZSgBP06mC8KbR5Cjz0e
eodXVHE24/R/x/0KRrzQ9zAVs1EULrhrobBkCp1Ftn/dyrJQyOFOeYuTKqT2ZxpL
CqfWVlrFLe6qNWtxWb6oXunWfuGvt0hlloPjzo74/TEOhjUNFxG52ucHOT0MUn5e
iXzBUSLbuW/8DlzCLY9ACdHsebcTpMRa0srSFthckRFinj0wQ1gFQbQcqWUtw18=
=J64o
-----END PGP SIGNATURE-----

```

**Comment by rvagg** [comment]
top of my head:

* for io.js and Node v4+ we'll have "Windows x64 Files: http://nodejs.org/dist/v3.3.0/win-x64/" (note "win-") and also "Windows x32 Files: http://nodejs.org/dist/v3.3.0/win-x32/", but for 0.10 and 0.12 releases we'll still use the same directories as before (i.e. / for 32-bit and /x64/ for 64-bit). Also, may as well change to "32-bit" and "64-bit" while you're there instead of "x64".
* There are both 32-bit and 64-bit Windows Installers, .msi files
* "Universal" is not correct for io.js or Node v4+ but will remain so for 0.10 and 0.12 releases—this goes also for the downloads pages for those so the templates need to change there as well. We're only shipping 64-bit binaries/installer for osx/darwin from io.js onward, "Universal" has both 32 and 64 munged together.
* What about links to the ARM builds? Also be aware that armv8 downloads should also be available soon, if not in v4.0.0, soon after
* We're still going to release io.js and it'd be good to be able to announce in the same way but it'll all be iojs.org and obviously s/node/iojs.

**Comment by phillipj** [comment]
Awesome feedback :+1:

Tbh I would like to extract the logic around files into something reusable, as the download matrix on the downloads page is pretty much exactly the same thing.

**Comment by mikeal** [comment]
This is awesome :)

**Comment by phillipj** [comment]
Decided to target node v4 in the first version of this script.

Just pushed necessary URL adjustments to the list of files, re-arranged the items and used the same terms and order as we do on the download matrix on out downloads page.

Are we going to have a unique URL per release on nodejs.org? Seems the old website did seeing the website URL in the release post, e.g. http://nodejs.org/docs/v0.12.7/

Just generated for v3.3.0:

```markdown
Windows 32-bit Installer: http://nodejs.org/dist/v3.3.0/node-v3.3.0-x86.msi

Windows 64-bit Installer: http://nodejs.org/dist/v3.3.0/node-v3.3.0-x64.msi

Windows 32-bit Binary: http://nodejs.org/dist/v3.3.0/win-x86/node.exe

Windows 64-bit Binary: http://nodejs.org/dist/v3.3.0/win-x64/node.exe

Mac OS X 64-bit Installer: http://nodejs.org/dist/v3.3.0/node-v3.3.0.pkg

Mac OS X 64-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-darwin-x64.tar.gz

Linux 32-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-x86.tar.gz

Linux 64-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-x64.tar.gz

SunOS 32-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-sunos-x86.tar.gz

SunOS 64-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-sunos-x64.tar.gz

ARMv6 32-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-armv6l.tar.gz

ARMv7 32-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-armv7l.tar.gz

ARMv8 64-bit Binary: http://nodejs.org/dist/v3.3.0/node-v3.3.0-linux-arm64.tar.gz

Source Code: http://nodejs.org/dist/v3.3.0/node-v3.3.0.tar.gz

Other release files: http://nodejs.org/dist/v3.3.0/

Website: http://nodejs.org/docs/v3.3.0/

Documentation: http://nodejs.org/docs/v3.3.0/api/
```

**Comment by phillipj** [comment]
This is ready to go for its first debut. Into master or node-4.0-release @fhemberger?

**Comment by fhemberger** [comment]
node-4.0-release, please. So we have everything we need in one place.

**Comment by phillipj** [comment]
Landed into node-4.0-release with fd14e76

**Pull request closed without merging**
